### ISSUE TITLE
Entra ID authentication missing username

### ISSUE THREAD

**Issue by jlenon** [microsoft/vscode-pgsql#30]
**Describe the bug**

Entra ID authentication does not allow me to set a separate username.  Azure Data Studio allowed this functionality, and our organisation requires this as access to databases is controlled by AD groups.

**To Reproduce**

1. In VSCode, click on '+ Add Connection' from POSTGRESQL extension pane,
2. Fill the form with connection details,
3. Choose 'AUTHENTICATION TYPE' 'Entra Auth',
4. Click on 'Add Entra Id' and login with your account,
5. Click on 'Save & Connect',
See the error.

**Expected behavior**

The expected behaviour is a new connection dialog that has the same options as Azure Data Studio - including username.

**Screenshots**

![Image](https://github.com/user-attachments/assets/3c4a1552-aea6-4465-9c73-be819ef1f179)

**VS Code version**

Version: 1.51.1 (system setup)
Commit: 95e6a0e2142d267ff827c86b8e8155fa055a73df
Date: 2025-02-08T00:29:26.043Z
VS Code: 1.82.0
Electron: 30.5.1
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Extension Logs**

N/A

A work around is to select username and password and put the AD group name as the username.  Then generate the password via the "az account get-access-token --resource-type oss-rdbms" command.

**Comment by lossyrob** [comment]
Hi @jlenon , thanks for reporting. As you pointed out the current version doesn't support alternate user names in the Entra authentication scenario, which is restricting user cases like yours. We're working on a fix and will release it asap.

Just so we can test this use case, can you describe the setup a bit more wrt the group name and IAM assignment to the database, so we can replicate?

**Comment by mmcfarland** [comment]
Hi folks, thanks for following this issue. We've published a pre-release version of the extension that includes the feature to provide your own Entra Username, so that it could be a group or guest account name, and not strictly the user email address for your logged-in Entra account. The form now also allows for switching different tenants.

We're looking for feedback on this feature before releasing it to a wider audience. If you're willing to test it out, please search for the extension in the Marketplace and click the "Switch to Pre-Release Version" button on the page. After you restart, you should be on version 1.5.0 (pre-release, you can always switch back to 1.4.2 stable). Please comment on this thread to let us know if this is working for your usecase, or any issues you experience. Thanks!

![Image](https://github.com/user-attachments/assets/4b66f315-e683-4dd9-9c43-ae1341172809)

**Comment by maftieu** [comment]
Quickly tested: connection is OK, querying is OK.
So works for me.

**Comment by lud-hu** [comment]
Hm, for me it's still failing with
`Connection error: connection failed: connection to server at "......", port 5432 failed: FATAL: password authentication failed for user "..."`
even though I switched to Entra Auth instead of password. 🤔

**Comment by mmcfarland** [comment]
Thanks for your feedback and validation help. This feature was included in stable release `1.6.0`.

**Comment by mmcfarland** [comment]
Thanks @drdamour -- to summarize what you experienced, is this accurate?

1. Have two Entra accounts added to the extension
2. Select one (in this case, in case ordering is important, you selected the 1st account in the list)
3. Connect, and the failure message indicate the oid being used for the token generation was the second in the list, the one that you had not selected.

Glad you have a workaround for this, but we'll try to reproduce and provide a fix.

**Comment by mmcfarland** [comment]
@drdamour I really appreciate the insights and you taking the time to follow up. I'll work on a reproduction and provide some updates when I have something.

**Comment by jlenon** [comment]
This update worked for me.  Thanks so much for adding this feature.
